micronaut.application.name=http-client-dispose-issue
micronaut.http.services.mocked-transactions.url=https://fa218db5-883c-4799-8802-c4cbba1f554f.mock.pstmn.io/transactions
micronaut.http.services.mocked-transactions.read-timeout=30s
micronaut.http.services.mocked-transactions.logger-name=mocked-transactions
logger.levels.mocked-transactions=TRACE
